export type clientDto = {
    id:string;
    userId:string;
    clientType:string;
    clientName:string;
    firstName:string;
    lastName:string;
    middleName:string;
    loginName:string;
    password:string,
    phoneNo:number;
    email:string;
    RoleName:string;
    companyId:string;
    companyName:string;
    Details:string;
    Website:string;
    address1:string;
    address2:string;
    city:string;
    state:string;
    country:string;
    DefaultTAT:number;
    FilePreferencePDF:boolean;
    FilePreferenceWord:boolean;
    FilePreferencePDFLink:boolean;
    ClientLogo:string;
    isDeleted:string;
    createdBy:string;
    modifyedBy:string;
    CreatedDateTime:Date,
    ModifiedDateTime:Date,
    filePreference:string;
}

export type updateClientDto = {
    id:string;
    userId:string;
    clientType:string;
    clientName:string;
    firstName:string;
    lastName:string;
    middleName:string;
    loginName:string;
    password:string,
    phoneNo:number;
    email:string;
    RoleName:string;
    companyId:string;
    companyName:string;
    Details:string;
    Website:string;
    address1:string;
    address2:string;
    city:string;
    state:string;
    country:string;
    DefaultTAT:number;
    FilePreferencePDF:boolean;
    FilePreferenceWord:boolean;
    FilePreferencePDFLink:boolean;
    ClientLogo:string;
    isDeleted:string;
    createdBy:string;
    modifyedBy:string;
    CreatedDateTime:Date,
    ModifiedDateTime:Date,
    filePreference:string,
    updatedBy:string
}