export type clientDto = {
    id:string;
    userId:string;
    ClientType:string;
    ClientName:string;
    FirstName:string;
    LastName:string;
    LoginName:string;
    Password:string,
    PhoneNo:string;
    Email:string;
    RoleName:string;
    CompanyId:string;
    CompanyName:string;
    Details:string;
    Website:string;
    Address1:string;
    Address2:string;
    City:string;
    StateId:string;
    CountryId:string;
    DefaultTAT:number;
    FilePreferencePDF:boolean;
    FilePreferenceWord:boolean;
    FilePreferencePDFLink:boolean;
    ClientLogo:string;
    IsDeleted:string;
    CreatedBy:string;
    ModifyedBy:string;
    CreatedDateTime:Date,
    ModifiedDateTime:Date,
    FilePreference:string;
}