export type clientDto = {
    id:string;
    userId:string;
    clientType:string;
    clientName:string;
    firstName:string;
    lastName:string;
    loginName:string;
    password:string,
    phoneNo:number;
    email:string;
    RoleName:string;
    companyId:string;
    companyName:string;
    Details:string;
    Website:string;
    address1:string;
    address2:string;
    city:string;
    stateId:string;
    CountryId:string;
    DefaultTAT:number;
    FilePreferencePDF:boolean;
    FilePreferenceWord:boolean;
    FilePreferencePDFLink:boolean;
    ClientLogo:string;
    isDeleted:string;
    createdBy:string;
    modifyedBy:string;
    CreatedDateTime:Date,
    ModifiedDateTime:Date,
    filePreference:string;
}