name: Build and deploy Node.js app to Azure Web App - mrs-api-prod

on:
  push:
    branches:
      - mrs-api-dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mrs-api-dev'
          slot-name: 'Development'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0E5AB20AC2774B09ADD77564B5C4ABB6 }}

      - name: Configure Environment Variables
        run: az webapp config appsettings set --resource-group your-resource-group --name mrs-api-prod --settings DB_HOST=${{ secrets.DB_HOST }} DB_NAME=${{ secrets.DB_NAME }} AWS_REGION=${{ secrets.AWS_REGION }} DB_UNAME=${{ secrets.DB_UNAME }} DB_PWD=${{ secrets.DB_PWD }}
